# Generated by Django 3.1.14 on 2023-05-10 10:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0003_pokemonentity'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemonentity',
            name='appeared_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 10, 10, 32, 52, 273785), verbose_name='Время появления'),
        ),
        migrations.AddField(
            model_name='pokemonentity',
            name='disappeared_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 10, 10, 32, 52, 273795), verbose_name='Время исчезновения'),
        ),
    ]
