# Generated by Django 4.2.1 on 2023-05-14 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0012_pokemonelementtype_alter_pokemon_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='parent',
            new_name='previous_evolution',
        ),
    ]
